INSERT INTO COURSES VALUES(1,4,'CSS','Intro to Computer Science');
INSERT INTO COURSES VALUES(2,5,'CSS','Data Structures');
INSERT INTO COURSES VALUES(3,6,'IT','Web and Mobile 2');
INSERT INTO COURSES VALUES(4,6,'LAW','Introduction of Law');
INSERT INTO COURSES VALUES(5,4,'BAA','Intro to Business Administration');
INSERT INTO COURSES VALUES(6,6,'MATH','Probability');

INSERT INTO STUDENT VALUES(1,'CSS','Smith','Ryan');
INSERT INTO STUDENT VALUES(2,'MATH','Heaven ','Browning');
INSERT INTO STUDENT VALUES(3,'LAW','Eugene ','Bauer');
INSERT INTO STUDENT VALUES(4,'BAA','Felix ','Davis');
INSERT INTO STUDENT VALUES(5,'IT','Yamilet ','Knight');
INSERT INTO STUDENT VALUES(6,'IT','Skylar ','Marsh');

INSERT INTO ENROLMENTS VALUES(1,1);
INSERT INTO ENROLMENTS VALUES(1,2);
INSERT INTO ENROLMENTS VALUES(2,6);
INSERT INTO ENROLMENTS VALUES(3,4);
INSERT INTO ENROLMENTS VALUES(4,1);
INSERT INTO ENROLMENTS VALUES(5,3);
INSERT INTO ENROLMENTS VALUES(5,1);
INSERT INTO ENROLMENTS VALUES(5,6);
INSERT INTO ENROLMENTS VALUES(6,3);
INSERT INTO ENROLMENTS VALUES(6,1);
INSERT INTO ENROLMENTS VALUES(6,6);