version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKER_PASS
          password: $DOCKER_USER  # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvnw package